#!/usr/bin/python3
# -*- coding:utf-8 -*-
import smtplib
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.header import Header
from selenium import webdriver
import time
import xlrd
import xlwt
import datetime



start = time.perf_counter()  # 程序开始时间
# 创建数据存储文件workbook 设置编码

workbookwt = xlwt.Workbook(encoding='utf-8')
# 创建worksheet
worksheet_bj = workbookwt.add_sheet('北京')
worksheet_sh = workbookwt.add_sheet('上海')
worksheet_sz = workbookwt.add_sheet('深圳')

# 打开读取文件
workbookrd = xlrd.open_workbook(r'D:\shenjing\workplace\beike\目标盘.xls')
# 根据sheet索引或者名称获取sheet内容
bj_list2 = workbookrd.sheet_by_name('北京')
# 北京sheet的第一列内容
bj_list = bj_list2.col_values(0)
print(bj_list)

sh_list2 = workbookrd.sheet_by_name('上海')
# 上海sheet的第一列内容
sh_list = sh_list2.col_values(0)
print(sh_list)

sz_list2 = workbookrd.sheet_by_name('深圳')
# 上海sheet的第一列内容
sz_list = sz_list2.col_values(0)
print(sz_list)

driver = webdriver.Chrome()
driver.maximize_window()  # 最大化浏览器

time.sleep(1)  # 暂停1秒钟
print("---------------------【开始爬取北京楼盘数据】----------------------")
for i in range(len(bj_list)):
    # 如果网页打开失败，重试3次
    for j in range(3):
        flag_url = False
        try:
            driver.get("https://bj.ke.com/ershoufang/rs" + bj_list[i])  # 通过get()方法，打开一个url站点
            print("【" + bj_list[i] + "】")
            time.sleep(2)  # 暂停2秒钟
            flag_url = True
        except:
            print("打开【" + bj_list[i] + "】页面"+str(j)+"次失败")
            flag_url = False
        if flag_url:  # 页面打开成功
            break
    # 判断楼盘吊顶卡片是否存在标志
    flag_semcard = False
    try:
        ele = driver.find_element_by_xpath("//*[@id='sem_card']/div/div[2]")
        flag_semcard = True
    except:
        flag_semcard = False
        worksheet_bj.write(i, 0, bj_list[i] + '没有楼盘吊顶卡片')
        print( "没有楼盘吊顶卡片")

    if flag_semcard:  # 楼盘卡片存在
        chushou = driver.find_element_by_xpath("//*[@id='sem_card']/div/div[2]/div[2]/div[2]/div[2]")
        chengjiao = driver.find_element_by_xpath("//*[@id='sem_card']/div/div[2]/div[2]/div[3]/div[2]")
        daikan = driver.find_element_by_xpath("//*[@id='sem_card']/div/div[2]/div[2]/div[4]/div[2]")
        print(" 正在出售" + chushou.text + " 近90天成交" + chengjiao.text + " 近30天带看" + daikan.text)
        # 写入excel ，参数对应 行, 列, 值
        worksheet_bj.write(i, 0, label=bj_list[i])  # 楼盘名
        worksheet_bj.write(i, 1, label=chushou.text)  # 正在出售
        worksheet_bj.write(i, 2, label=chengjiao.text)  # 近90天成交
        worksheet_bj.write(i, 3, label=daikan.text)  # 近30天带看
        time.sleep(1)  # 暂停2秒钟

time.sleep(1)  # 暂停1秒钟
print("---------------------【开始爬取上海楼盘数据】----------------------")
for i in range(len(sh_list)):
    # 如果网页打开失败，重试3次
    for j in range(3):
        flag_url = False
        try:
            driver.get("https://sh.ke.com/ershoufang/rs" + sh_list[i])  # 通过get()方法，打开一个url站点
            print("【" + sh_list[i] + "】")
            time.sleep(2)  # 暂停2秒钟
            flag_url = True
        except:
            print("打开【" + sh_list[i] + "】页面" + str(j) + "次失败")
            flag_url = False
        if flag_url:  # 页面打开成功
            break

    flag = False  # 判断楼盘吊顶卡片是否存在标志
    try:
        ele = driver.find_element_by_xpath("//*[@id='sem_card']/div/div[2]")
        flag = True
    except:
        flag = False
        worksheet_sh.write(i, 0, sh_list[i] + '没有楼盘吊顶卡片')
        print("没有楼盘吊顶卡片")

    if flag:  # 楼盘卡片存在
        chushou = driver.find_element_by_xpath("//*[@id='sem_card']/div/div[2]/div[2]/div[2]/div[2]")
        chengjiao = driver.find_element_by_xpath("//*[@id='sem_card']/div/div[2]/div[2]/div[3]/div[2]")
        daikan = driver.find_element_by_xpath("//*[@id='sem_card']/div/div[2]/div[2]/div[4]/div[2]")
        print(" 正在出售" + chushou.text + " 近90天成交" + chengjiao.text + " 近30天带看" + daikan.text)
        # 写入excel ，参数对应 行, 列, 值
        worksheet_sh.write(i, 0, label=sh_list[i])  # 楼盘名
        worksheet_sh.write(i, 1, label=chushou.text)  # 正在出售
        worksheet_sh.write(i, 2, label=chengjiao.text)  # 近90天成交
        worksheet_sh.write(i, 3, label=daikan.text)  # 近30天带看
        time.sleep(1)  # 暂停2秒钟


time.sleep(1)  # 暂停1秒钟
print("---------------------【开始爬取深圳楼盘数据】----------------------")
for i in range(len(sz_list)):
    # 如果网页打开失败，重试3次
    for j in range(3):
        flag_url = False
        try:
            driver.get("https://sz.ke.com/ershoufang/rs" + sz_list[i])  # 通过get()方法，打开一个url站点
            print("【" + sz_list[i] + "】")
            time.sleep(2)  # 暂停2秒钟
            flag_url = True
        except:
            print("打开【" + sz_list[i] + "】页面" + str(j) + "次失败")
            flag_url = False
        if flag_url:  # 页面打开成功
            break

    flag = False  # 判断楼盘吊顶卡片是否存在标志
    try:
        ele = driver.find_element_by_xpath("//*[@id='sem_card']/div/div[2]")
        flag = True
    except:
        flag = False
        worksheet_sz.write(i, 0, sz_list[i]+'没有楼盘吊顶卡片')
        print("没有楼盘吊顶卡片")

    if flag:  # 楼盘卡片存在
        chushou = driver.find_element_by_xpath("//*[@id='sem_card']/div/div[2]/div[2]/div[2]/div[2]")
        chengjiao = driver.find_element_by_xpath("//*[@id='sem_card']/div/div[2]/div[2]/div[3]/div[2]")
        daikan = driver.find_element_by_xpath("//*[@id='sem_card']/div/div[2]/div[2]/div[4]/div[2]")
        print(" 正在出售" + chushou.text + " 近90天成交" + chengjiao.text + " 近30天带看" + daikan.text)
        # 写入excel ，参数对应 行, 列, 值
        worksheet_sz.write(i, 0, label=sz_list[i])  # 楼盘名
        worksheet_sz.write(i, 1, label=chushou.text)  # 正在出售
        worksheet_sz.write(i, 2, label=chengjiao.text)  # 近90天成交
        worksheet_sz.write(i, 3, label=daikan.text)  # 近30天带看
        time.sleep(1)  # 暂停2秒钟

# 保存
workbookwt.save('Excel_data.xls')


# 第三方 SMTP 服务
# mail_host="smtp.XXX.com"  #设置服务器
mail_host = "mail.lizihang.com"
mail_user = "shenjing@lizihang.com"  # 用户名
mail_pass = "landz@123"  # 口令

sender = 'shenjing@lizihang.com'  # 发送邮件
receivers = ['shenjing@lizihang.com','wangyuling@lizihang.com']  # 接收邮件，可设置为你的QQ邮箱或者其他邮箱 ,'wangyuling@lizihang.com'
nowTime = datetime.datetime.now().strftime('%Y-%m-%d')  # 现在
message = MIMEMultipart()

# 文本内容
mail_msg = """
<h2>贝壳目标盘数据</h2>
<p><a href="https://bj.ke.com/">这是贝壳网链接</a></p>"""
textApart = MIMEText(mail_msg, 'html', 'utf-8')
message.attach(textApart)

# 构造附件
exl_file = open(r'D:\shenjing\workplace\beike\Excel_data.xls', 'rb').read()
exl = MIMEText(exl_file, 'base64', 'utf-8')
exl["Content-Type"] = 'application/octet-stream'
# 以下代码可以重命名附件为Excel_test.xls
exl.add_header('Content-Disposition', 'attachment', filename=('beikeData' + str(nowTime) + '.xls'))
message.attach(exl)

message['From'] = Header("邮件自动发送--贝壳目标盘数据", 'utf-8')
message['To'] = Header("王玉玲", 'utf-8')
message['Subject'] = Header('贝壳目标盘', 'utf-8')


try:
    smtpObj = smtplib.SMTP()
    smtpObj.connect(mail_host, 25)  # 25 为 SMTP 端口号
    smtpObj.login(mail_user, mail_pass)
    smtpObj.sendmail(sender, receivers, message.as_string())
    print("邮件发送成功")
except smtplib.SMTPException:
    print("Error: 无法发送邮件")

driver.quit()

end = time.perf_counter()  # 结束时间 单位秒
print("运行耗时", end - start)  # 北京楼盘+房屋 运行耗时 23997.9224209

# 北京楼盘运行耗时 939.9924796
# 三地楼盘 运行耗时 1402.1540671999999



